version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.2

jobs:
  test:
    docker:
      - image: cimg/node:13.12-browsers
    resource_class: medium
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

workflows:
  main:
    jobs:
      - test
